# Generated by Django 4.2.1 on 2023-07-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_author_blog_blogger_comment_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post_date']},
        ),
    ]
