# Generated by Django 4.2.1 on 2023-07-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options_alter_blogger_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post_date']},
        ),
    ]
