# Generated by Django 4.2.1 on 2023-07-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_options_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_date'], 'permissions': (('can_edit_blog', 'Can change blog'),)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post_date'], 'permissions': (('can_delete_comment', 'Can delete comment'),)},
        ),
    ]
